---
permalink: online-help/concept-constituent-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: Die Seite „FlexGroup-Datei/Performance-Explorer“ enthält detaillierte Leistungsinformationen für die ausgewählte Komponente. 
---
= Seite „Konstituierendes Volumen/Performance Explorer“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite „FlexGroup-Datei/Performance-Explorer“ enthält detaillierte Leistungsinformationen für die ausgewählte Komponente.

Auf der Seite „Constituent Volume/Performance Explorer“ können Sie die Performance der Komponente während eines bestimmten Zeitraums verfolgen und vergleichen. Dies hilft bei der Fehlerbehebung und Feinabstimmung der Performance eines FlexGroup-Volumes und seiner zusammengehörigen Volumes.

Mithilfe der Funktion „Anzeigen und Vergleichen“ können Sie die Performance dieses zusammengehörigen Volumes mit folgenden Punkten vergleichen:

* Das Aggregat, in dem sich das zusammengehörige Volume befindet
* Der Storage-VM, auf der sich das zusammengehörige Volume befindet
* Das FlexGroup Volume, zu dem das zusammengehörige Volume gehört
* Andere Volumes, die sich auf dem gleichen Aggregat befinden


Auf der Seite „Datei/Performance Explorer“ können Sie folgende Funktionen ausführen:

* Zeigen Sie Probleme mit Schwellenwerten und deren Details an
* Verfolgen und vergleichen Sie die Performance-Daten der einzelnen Bestandteile
* Untersuchung und Behebung von Problemen mit Schwellenwerten
* Untersuchung und Behebung von Performance-Problemen


[NOTE]
====
Für Datensicherungs-Volumes (DP) werden nur Zählerwerte für den benutzergenerierten Datenverkehr angezeigt.

====