---
permalink: online-help/concept-node-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: Die Seite Node/Performance Explorer bietet eine detaillierte Performance-Übersicht über alle Nodes innerhalb eines Clusters. 
---
= Seite „Node/Performance Explorer“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite Node/Performance Explorer bietet eine detaillierte Performance-Übersicht über alle Nodes innerhalb eines Clusters.

Auf der Seite Node/Performance Explorer können Sie die Knoten-Performance in einem bestimmten Zeitraum verfolgen und vergleichen. Dies hilft Ihnen bei der Fehlerbehebung und Feinabstimmung der Performance Ihrer Knoten.

Mit der Funktion „Anzeigen und Vergleichen“ können Sie die Performance dieses Knotens mit den folgenden vergleichen:

* Anderen Nodes im selben Cluster
* Die Aggregate auf dem Node
* Die Ports auf dem Node


Auf der Seite Node/Performance Explorer können Sie:

* Zeigen Sie Probleme mit Schwellenwerten und deren Details an
* Verfolgen und Vergleichen von Node-Performance-Daten
* Untersuchung und Behebung von Problemen mit Schwellenwerten
* Untersuchung und Behebung von Performance-Problemen

