---
permalink: online-help/concept-cluster-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: Die Seite „Cluster/Performance Explorer“ bietet eine detaillierte Performance-Übersicht über alle Cluster, die von Unified Manager gemanagt werden. 
---
= Seite „Cluster/Performance Explorer“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite „Cluster/Performance Explorer“ bietet eine detaillierte Performance-Übersicht über alle Cluster, die von Unified Manager gemanagt werden.

Auf der Seite „Cluster/Performance Explorer“ können Sie die Cluster-Performance nachverfolgen und die Objekte in diesem Cluster während eines bestimmten Zeitraums vergleichen. Dies erleichtert die Fehlerbehebung und Feinanpassung der Performance eines Clusters.

Mithilfe der Funktion „View and Compare“ können Sie die Performance des Clusters mit vergleichen:

* Die Nodes in diesem Cluster
* Die Storage-VMs dieses Clusters
* Die Aggregate auf diesem Cluster


Auf der Seite Cluster/Performance Explorer können Sie:

* Zeigen Sie Probleme mit Schwellenwerten und deren Details an
* Nachverfolgung von Cluster-Performance-Daten
* Untersuchung und Behebung von Problemen mit Schwellenwerten
* Untersuchung und Behebung von Performance-Problemen

