---
permalink: online-help/concept-aggregate-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: Die Seite „Aggregate/Performance Explorer“ bietet eine detaillierte Performance-Übersicht über alle Aggregate in einem Cluster. 
---
= Explorer-Seite für Aggregat/Performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite „Aggregate/Performance Explorer“ bietet eine detaillierte Performance-Übersicht über alle Aggregate in einem Cluster.

Auf der Seite „Aggregat/Performance Explorer“ können Sie die Aggregat-Performance in einem bestimmten Zeitraum nachverfolgen und vergleichen. Dies hilft Ihnen bei der Fehlerbehebung und Feinabstimmung der Performance eines Aggregats.

[NOTE]
====
Root-Aggregate werden auf dieser Seite nicht angezeigt.

====
Mithilfe der Funktion „Anzeigen und Vergleichen“ können Sie die Performance dieses Aggregats mit folgenden vergleichen:

* Anderer Aggregate auf demselben Node
* Anderen Aggregaten auf demselben Cluster
* Der Node, auf dem sich das Aggregat befindet
* Alle Nodes auf dem Cluster, die dieses Aggregat verwenden
* Die Volumes in diesem Aggregat


Auf der Seite „Aggregate/Performance Explorer“ können Sie

* Zeigen Sie Probleme mit Schwellenwerten und deren Details an
* Verfolgen und Vergleichen von Aggregat-Performance-Daten
* Untersuchung und Behebung von Problemen mit Schwellenwerten
* Untersuchung und Behebung von Performance-Problemen

