---
permalink: online-help/concept-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: Diese Seite bietet detaillierte Performance-Informationen für ein Volume in einem Cluster. Der Titel dieser Seite hängt davon ab, ob Sie ein FlexVol-Volume oder ein FlexGroup-Volume anzeigen. 
---
= Volume/Performance Explorer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese Seite bietet detaillierte Performance-Informationen für ein Volume in einem Cluster. Der Titel dieser Seite hängt davon ab, ob Sie ein FlexVol-Volume oder ein FlexGroup-Volume anzeigen.

Auf der Seite „Volume/Performance Explorer“ können Sie die Volume-Performance während eines bestimmten Zeitraums verfolgen und vergleichen. So können Sie Fehler beheben und die Volume-Performance optimieren.

[NOTE]
====
Root-Volumes werden auf dieser Seite nicht angezeigt.

====
Verwenden der Funktion „Anzeigen und Vergleichen“:

* Bei FlexVol Volumes können Sie die Performance dieses Volumes mit vergleichen:
+
** Andere Volumes auf demselben Aggregat
** Andere Volumes in derselben QoS-Richtliniengruppe
** Das Aggregat, auf dem sich dieses Volume befindet
** Der Storage-VM, auf der sich das Volume befindet
** Die LUNs, die sich auf diesem Volume befinden


* Bei FlexGroup Volumes können Sie die Performance dieser FlexGroup mit vergleichen:
+
** Die Aggregate, auf denen sich die FlexGroup befindet
** Die Storage-VM, auf der sich die FlexGroup befindet
** Die zusammengehörigen Volumes der FlexGroup




Die Statistiken in den Diagrammen werden nach jedem Erfassungszeitraum aktualisiert, der standardmäßig alle 5 Minuten beträgt. Die Auswahl von Statistiken zur Ansicht bietet eine Option, um die über die vorherige Stunde gemittelten Statistiken anzuzeigen. Durch diese Funktionalität können Sie das Latenzdiagramm zur Unterstützung des NetApp“-Programms`Performance Guarantee` anzeigen.

Auf der Seite Volume/Performance Explorer können Sie:

* Zeigen Sie Probleme mit Schwellenwerten und deren Details an
* Verfolgen und Vergleichen von Volume Performance-Daten
* Untersuchung und Behebung von Problemen mit Schwellenwerten
* Untersuchung und Behebung von Performance-Problemen
* Starten Sie System Manager, um eine Konfigurationsänderung für das Volume vorzunehmen
+
Die Schaltfläche *Lautstärke konfigurieren* steht zur Verfügung, wenn Sie mit der Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ bei Unified Manager angemeldet sind, und wenn Sie ONTAP 9.5 oder höher verwenden.



[NOTE]
====
Für Datensicherungs-Volumes (DP) werden nur Zählerwerte für den benutzergenerierten Datenverkehr angezeigt.

====