---
permalink: online-help/reference-qtree-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite „Qtree-Schwellenwerte“ können Sie globale Kapazitätsschwellenwerte für überwachte qtrees konfigurieren. Ereignisse werden nur dann für einen qtree erzeugt, wenn ein qtree Kontingent oder eine Standard-Quote auf dem qtree festgelegt wurde. Ereignisse werden nicht generiert, wenn der in einem Benutzerkontingent oder Gruppenkontingent definierte Speicherplatz den Schwellenwert überschritten hat. 
---
= Seite „qtree Schwellenwerte“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Qtree-Schwellenwerte“ können Sie globale Kapazitätsschwellenwerte für überwachte qtrees konfigurieren. Ereignisse werden nur dann für einen qtree erzeugt, wenn ein qtree Kontingent oder eine Standard-Quote auf dem qtree festgelegt wurde. Ereignisse werden nicht generiert, wenn der in einem Benutzerkontingent oder Gruppenkontingent definierte Speicherplatz den Schwellenwert überschritten hat.

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.

Ereignisse werden erzeugt, wenn ein Schwellenwert überschritten wird. Sie können für solche Ereignisse Korrekturmaßnahmen ergreifen.



== Kapazität

Im Kapazitätsbereich können Sie die folgenden qtree-Kapazitätsschwellenwerte festlegen.

* *Raum Fast Voll*
+
Gibt den Prozentsatz an, bei dem ein qtree als nahezu voll erachtet wird:

+
** Standardwert: 80 Prozent
+
Der Wert für diesen Schwellenwert muss niedriger sein als der Wert für den Qtree Full Schwellenwert.

** Event generiert: Qtree fast voll
** Ereignis Schweregrad: Warnung


* *Raum Voll*
+
Gibt den Prozentsatz an, bei dem ein qtree als voll erachtet wird:

+
** Standardwert: 90 Prozent
** Ereignis generiert: Qtree voll
** Ereignis Schweregrad: Fehler



