---
permalink: online-help/reference-nvme-namespace-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite NVMe Namespace/Performance Information können Sie eine Liste der physischen und logischen Attribute des Namespace anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen. 
---
= Informationsseite für NVMe Namespace/Performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite NVMe Namespace/Performance Information können Sie eine Liste der physischen und logischen Attribute des Namespace anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen.



== Attribute für NVMe Namespace

* * Cluster*
+
Der Name des Clusters, zu dem der Namespace gehört. Sie können auf den Namen klicken, um in der Seite „Cluster/Performance Explorer“ Cluster-Details anzuzeigen.

* * Kapazität (frei/gesamt)*
+
Die gesamte Storage-Kapazität des Namespace und die derzeit verfügbare Speichermenge.

* *Knoten*
+
Der Name des Node, auf dem sich der Namespace befindet. Sie können auf den Namen klicken, um Node-Details auf der Seite Node/Performance Explorer anzuzeigen.

* *Pfad*
+
Der vollständige Pfad des NVMe Namespace beispielsweise `/vol/vol1/namespace1`.

* *Bundesland*
+
Der Status des Namespace. Gültige Status können „Online“, „Offline“, „NV-Fehler“ und „space-error“ sein.

* *Subsystem*
+
Das Subsystem des Namespace.

* *Storage VM*
+
Der Name der SVM, zu der der Namespace gehört. Sie können auf den Namen klicken, um Details zu SVMs auf der Seite Storage VM/Performance Explorer anzuzeigen.

* *Lautstärke*
+
Der Name des Volumes, zu dem der Namespace gehört. Sie können auf den Namen klicken, um die Volume-Details auf der Seite Volume/Performance Explorer anzuzeigen.


