---
permalink: online-help/reference-capacity-all-qtrees-view.html 
sidebar: sidebar 
keywords:  
summary: 'Die Kapazität: Die Ansicht „qtrees“ ermöglicht Ihnen, Informationen zur Kapazität und Auslastung von qtrees in allen Clustern anzuzeigen. Diese Informationen geben Ihnen die Möglichkeit, mögliche Kapazitätsrisiken zu verstehen sowie den konfigurierten und verwendeten Festplattenprozentsatz und die Anzahl der Dateien anzuzeigen.' 
---
= Kapazität: Alle Qtrees-Ansicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Kapazität: Die Ansicht „qtrees“ ermöglicht Ihnen, Informationen zur Kapazität und Auslastung von qtrees in allen Clustern anzuzeigen. Diese Informationen geben Ihnen die Möglichkeit, mögliche Kapazitätsrisiken zu verstehen sowie den konfigurierten und verwendeten Festplattenprozentsatz und die Anzahl der Dateien anzuzeigen.

Standardmäßig werden Objekte auf den Ansichtsseiten nach Wichtigkeit des Ereignisses sortiert. Objekte mit kritischen Ereignissen werden zuerst aufgeführt und Objekte mit Warnmeldungen werden als zweites aufgeführt. Dies bietet eine unmittelbare visuelle Darstellung von Problemen, die behoben werden müssen.

Mit den Steuerelementen oben auf der Seite können Sie eine bestimmte Ansicht auswählen (für Zustand, Leistung, Kapazität usw.). Führen Sie Suchen durch, um bestimmte Objekte zu finden, erstellen und anwenden Sie Filter, um die Liste der angezeigten Daten einzugrenzen, Spalten auf der Seite hinzuzufügen/zu entfernen/neu zu ordnen, Und exportieren Sie die Daten auf der Seite in A `.csv`, `.pdf`, Oder `.xlsx` Datei: Nachdem Sie die Seite angepasst haben, können Sie die Ergebnisse als benutzerdefinierte Ansicht speichern und anschließend einen Bericht dieser Daten erstellen und regelmäßig per E-Mail senden.

Mit der Schaltfläche *Schwellenwert bearbeiten* können Sie die Einstellungen für Kapazitätsschwellenwerte für eine oder mehrere qtrees anpassen.

Siehe xref:reference-qtree-capacity-fields.adoc[Felder für die qtree-Kapazität] Für Beschreibungen aller Felder auf dieser Seite.
