---
permalink: online-help/reference-edit-cluster-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Im Dialogfeld Cluster bearbeiten können Sie die Verbindungseinstellungen eines vorhandenen Clusters, einschließlich IP-Adresse, Port und Protokoll, ändern. 
---
= Dialogfeld Cluster bearbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Cluster bearbeiten können Sie die Verbindungseinstellungen eines vorhandenen Clusters, einschließlich IP-Adresse, Port und Protokoll, ändern.

Sie können die folgenden Felder bearbeiten:

* *Hostname oder IP-Adresse*
+
Ermöglicht Ihnen, den FQDN, den Kurznamen oder die IP-Adresse (IPv4 oder IPv6) der Cluster-Management-LIF anzugeben, die zum Herstellen einer Verbindung zum Cluster verwendet wird.

* *Benutzername*
+
Ermöglicht Ihnen, einen Benutzernamen anzugeben, der zum Anmelden beim Cluster verwendet werden kann.

* *Passwort*
+
Ermöglicht Ihnen die Angabe eines Passworts für den angegebenen Benutzernamen.

* *Port*
+
Ermöglicht Ihnen, die Portnummer anzugeben, die zum Herstellen der Verbindung mit dem Cluster verwendet wird. Der Standardport ist 443 für HTTPS.


