---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: 'Die Kapazität: Alle Cluster-Ansichten ermöglichen die Anzeige zusammengefasste Informationen zur Storage-Kapazität und Auslastung in allen Clustern. Anhand dieser Informationen werden mögliche Kapazitätsrisiken identifiziert und die Workloads neu ausgerichtet.' 
---
= Kapazität: Alle Cluster-Ansicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Kapazität: Alle Cluster-Ansichten ermöglichen die Anzeige zusammengefasste Informationen zur Storage-Kapazität und Auslastung in allen Clustern. Anhand dieser Informationen werden mögliche Kapazitätsrisiken identifiziert und die Workloads neu ausgerichtet.

Mit den Steuerelementen oben auf der Seite können Sie eine bestimmte Ansicht auswählen (für Zustand, Leistung, Kapazität usw.). Führen Sie Suchen durch, um bestimmte Objekte zu finden, erstellen und anwenden Sie Filter, um die Liste der angezeigten Daten einzugrenzen, Spalten auf der Seite hinzuzufügen/zu entfernen/neu zu ordnen, Und exportieren Sie die Daten auf der Seite in A `.csv`, `.pdf`, Oder `.xlsx` Datei: Nachdem Sie die Seite angepasst haben, können Sie die Ergebnisse als benutzerdefinierte Ansicht speichern und anschließend einen Bericht dieser Daten erstellen und regelmäßig per E-Mail senden.

Siehe xref:reference-cluster-capacity-fields.adoc[Felder für die Cluster-Kapazität] Für Beschreibungen aller Felder auf dieser Seite.
