---
permalink: online-help/reference-health-all-svms-view.html 
sidebar: sidebar 
keywords:  
summary: 'Der Systemzustand: Alle Storage VMs Ansicht bietet Ihnen detaillierte Informationen über die von Ihnen überwachten Storage Virtual Machines \(SVMs\).' 
---
= Systemzustand: Ansicht aller Storage VMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Status: Alle Storage VMs Ansicht ermöglicht Ihnen, detaillierte Informationen zu den von Ihnen überwachten Storage Virtual Machines (SVMs) anzuzeigen.

Standardmäßig werden Objekte auf den Ansichtsseiten nach Wichtigkeit des Ereignisses sortiert. Objekte mit kritischen Ereignissen werden zuerst aufgeführt und Objekte mit Warnmeldungen werden als zweites aufgeführt. Dies bietet eine unmittelbare visuelle Darstellung von Problemen, die behoben werden müssen. Jede Storage VM im Storage VMs-Grid verfügt über Links zu ONTAP System Manager. Über diesen Link können Sie dieselbe Schutzbeziehung in ONTAP System Manager anzeigen.

Mit den Steuerelementen oben auf der Seite können Sie eine bestimmte Ansicht auswählen (für Zustand, Leistung, Kapazität usw.). Führen Sie Suchen durch, um bestimmte Objekte zu finden, erstellen und anwenden Sie Filter, um die Liste der angezeigten Daten einzugrenzen, Spalten auf der Seite hinzuzufügen/zu entfernen/neu zu ordnen, Und exportieren Sie die Daten auf der Seite in A `.csv`, `.pdf`, Oder `.xlsx` Datei: Nachdem Sie die Seite angepasst haben, können Sie die Ergebnisse als benutzerdefinierte Ansicht speichern und anschließend einen Bericht dieser Daten erstellen und regelmäßig per E-Mail senden.

Sie können eine SVM mit einer vordefinierten Anmerkung verknüpfen, indem Sie die Schaltfläche *Annotate* verwenden.

Siehe xref:reference-svm-health-fields.adoc[Felder für den SVM-Zustand] Für Beschreibungen aller Felder auf dieser Seite.
