---
permalink: online-help/reference-cluster-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite Cluster/Performance Information können Sie eine Liste der physischen und logischen Attribute des Clusters anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen. 
---
= Cluster/Performance Information page
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Cluster/Performance Information können Sie eine Liste der physischen und logischen Attribute des Clusters anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen.



== Cluster-Attribute

* *Management Network Interface*
+
Der Name der Cluster-Management-LIF und, ob das LIF derzeit verfügbar ist (up), oder nicht (Down).

* *IP-Adresse*
+
Die IPv4- oder IPv6-Adresse der Cluster-Management-LIF.

* *FQDN*
+
Der vollständig qualifizierte Domain-Name (FQDN) der Cluster-Management-LIF.

* *Betriebssystemversion*
+
Die Version der auf dem Cluster installierten ONTAP Software.

+
[NOTE]
====
Falls unterschiedliche Versionen der ONTAP Software auf den Nodes im Cluster installiert werden, ist die aufgeführte Version die niedrigste Versionsnummer. Überprüfen Sie die Seite Node/Performance Information, um die Version der auf jedem Node installierten ONTAP Software anzuzeigen.

====
* *Seriennummer*
+
Die eindeutige Identifikationsnummer des Clusters.

* *Modell / Familie*
+
Die Modellnummer und Modellfamilie aller Nodes im Cluster.

* * Kapazität (frei/gesamt)*
+
Den gesamten für den Cluster verfügbaren Speicher in Gigabyte und die derzeit verfügbare Menge an Speicherplatz.

* *Verwendeter Logischer Raum*
+
Die tatsächliche Größe der Daten, die auf diesen Aggregaten dieses Clusters gespeichert werden, ohne die Einsparungen durch die ONTAP Storage-Effizienztechnologien zu verwenden.

* *Erlaubte Protokolle*
+
Liste aller Protokolle, die von diesem Cluster gewartet werden können. Zu den verfügbaren Protokollen gehören FC/FCoE, iSCSI, HTTP, NVMe, NDMP, NFS und CIFS.

* *Knoten*
+
Die Anzahl der Nodes in diesem Cluster. Sie können auf die Nummer klicken, um auf der Seite „Performance/Nodes-Inventar“ die Nodes anzuzeigen.

* *Storage VM*
+
Die Anzahl der SVMs in diesem Cluster Sie können auf der Seite „Performance/Storage VMs Inventory“ auf die Nummer klicken, um die SVMs anzuzeigen.

* *Netzwerkschnittstellen*
+
Die Anzahl der LIFs in diesem Cluster. Sie können auf die Nummer klicken, um die LIFs auf der Seite „Performance/LIFs Inventar“ anzuzeigen.

* *Kontakt / Standort*
+
Falls verfügbar: Der Name des Storage-Administrators, der bezüglich des Clusters und den Standort des Clusters kontaktiert werden soll.


