---
permalink: online-help/reference-capacity-all-aggregates-view.html 
sidebar: sidebar 
keywords:  
summary: 'Die Kapazität: Alle Aggregatansicht ermöglicht es Ihnen, Informationen über Kapazität und Auslastung von Aggregaten in allen Clustern anzuzeigen. Diese Informationen geben Ihnen die Möglichkeit, mögliche Kapazitätsrisiken zu verstehen und die konfigurierte, genutzte und nicht genutzte Kapazität von Aggregaten anzuzeigen.' 
---
= Kapazität: Alle Aggregate anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Kapazität: Alle Aggregatansicht ermöglicht es Ihnen, Informationen über Kapazität und Auslastung von Aggregaten in allen Clustern anzuzeigen. Diese Informationen geben Ihnen die Möglichkeit, mögliche Kapazitätsrisiken zu verstehen und die konfigurierte, genutzte und nicht genutzte Kapazität von Aggregaten anzuzeigen.

Mit den Steuerelementen oben auf der Seite können Sie eine bestimmte Ansicht auswählen (für Zustand, Leistung, Kapazität usw.). Führen Sie Suchen durch, um bestimmte Objekte zu finden, erstellen und anwenden Sie Filter, um die Liste der angezeigten Daten einzugrenzen, Spalten auf der Seite hinzuzufügen/zu entfernen/neu zu ordnen, Und exportieren Sie die Daten auf der Seite in A `.csv`, `.pdf`, Oder `.xlsx` Datei: Nachdem Sie die Seite angepasst haben, können Sie die Ergebnisse als benutzerdefinierte Ansicht speichern und anschließend einen Bericht dieser Daten erstellen und regelmäßig per E-Mail senden.

Siehe xref:reference-aggregate-capacity-fields.adoc[Felder für die Aggregatskapazität] Für Beschreibungen aller Felder auf dieser Seite.
