---
permalink: online-help/reference-network-interface-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 'Auf der Seite Netzwerkschnittstelle/Leistungsinformationen können Sie eine Liste der konfigurierten Attribute der Netzwerkschnittstelle \(LIF\) anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen.' 
---
= Netzwerkschnittstelle/Leistungsinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Netzwerkschnittstelle/Leistungsinformationen können Sie eine Liste der konfigurierten Attribute der Netzwerkschnittstelle (LIF) anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen.



== Attribute der Netzwerkschnittstelle

* *IP-Adresse*
+
Die dem LIF zugewiesene IPv4- oder IPv6-Adresse. Einem LIF kann mehrere IP-Adressen zugewiesen sein.

* * Rolle*
+
Die Rolle bestimmt die Art des Datenverkehrs, der über das LIF unterstützt wird.

+
LIFs können eine der folgenden Rollen aufweisen:

+
** Daten
** Cluster
** Node-Management
** Intercluster


* *Failover-Gruppe*
+
Der Name der Failover-Gruppe, die der Netzwerkschnittstelle zugewiesen ist.

+
Dieses Feld gilt nur für Netzwerk-LIFs, nicht für SAN (FC/ISCSI) und NVMe LIFs.

* *Failover-Richtlinie*
+
Der Name der Failover-Richtlinie, die dem LIF zugewiesen ist.

+
Dieses Feld gilt nur für Netzwerk-LIFs, nicht für SAN (FC/ISCSI) und NVMe LIFs.

* * Home Port*
+
Der Name des Node und des Ports, der als Home-Port für diese Schnittstelle definiert wurde. Sie können auf den Namen klicken, um die Portdetails auf der Seite Port/Performance Explorer anzuzeigen.

* *Aktueller Port*
+
Der Name des Node und des Ports, auf dem die Schnittstelle derzeit gehostet wird. Sie können auf den Namen klicken, um die Portdetails auf der Seite Port/Performance Explorer anzuzeigen.


