---
permalink: online-help/task-configuring-windows-host-machine.html 
sidebar: sidebar 
keywords: NetApp Snapshot backup for Windows,configuring Windows host machine 
summary: Sie müssen Ihren Windows Host Machine konfigurieren, auf dem Active IQ Unified Manager installiert ist, um das NetApp Snapshot Backup vorzubereiten. Um den Microsoft iSCSI-Initiator auf einem Windows-Hostcomputer zu starten, geben Sie in der Suchleiste „iscsi“ ein und klicken Sie auf iSCSI-Initiator. 
---
= Windows-Hostcomputer wird konfiguriert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Ihren Windows Host Machine konfigurieren, auf dem Active IQ Unified Manager installiert ist, um das NetApp Snapshot Backup vorzubereiten. Um den Microsoft iSCSI-Initiator auf einem Windows-Hostcomputer zu starten, geben Sie in der Suchleiste „`iscsi`“ ein und klicken Sie auf *iSCSI-Initiator*.



== Bevor Sie beginnen

Sie sollten alle früheren Konfigurationen auf dem Host-Rechner bereinigen.



== Über diese Aufgabe

Wenn Sie versuchen, den iSCSI-Initiator bei einer Neuinstallation von Windows zu starten, werden Sie zur Bestätigung aufgefordert. Anschließend wird das Dialogfeld iSCSI-Eigenschaften angezeigt. Wenn es sich um eine vorhandene Windows-Installation handelt, wird das Dialogfeld iSCSI-Eigenschaften mit einem Ziel angezeigt, das entweder inaktiv ist oder versucht, eine Verbindung herzustellen. Sie müssen also sicherstellen, dass alle vorherigen Konfigurationen auf dem Windows-Host entfernt werden.



== Schritte

. Entfernen Sie alle früheren Konfigurationen auf dem Host-Rechner.
. Entdecken Sie das Zielportal.
. Stellen Sie eine Verbindung zum Zielportal her.
. Multipath wird mit dem Zielportal verbunden.
. Ermitteln Sie die beiden LIFs.
. Ermitteln Sie die LUN, die auf dem Windows-Rechner als Gerät konfiguriert ist.
. Konfigurieren Sie die erkannte LUN als neues Volume-Laufwerk in Windows.

