---
permalink: online-help/task-downloading-an-https-certificate-signing-request-ocf.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine Zertifizierungssignierungsanforderung für das aktuelle HTTPS-Sicherheitszertifikat herunterladen, so dass Sie die Datei einer Zertifizierungsstelle zum Signieren zur Verfügung stellen können. Ein von einer Zertifizierungsstelle signiertes Zertifikat hilft bei der Verhinderung von man-in-the-Middle-Angriffen und bietet besseren Schutz als ein selbstsigniertes Zertifikat. 
---
= Herunterladen einer Anforderung zum Signieren eines HTTPS-Zertifikats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Zertifizierungssignierungsanforderung für das aktuelle HTTPS-Sicherheitszertifikat herunterladen, so dass Sie die Datei einer Zertifizierungsstelle zum Signieren zur Verfügung stellen können. Ein von einer Zertifizierungsstelle signiertes Zertifikat hilft bei der Verhinderung von man-in-the-Middle-Angriffen und bietet besseren Schutz als ein selbstsigniertes Zertifikat.



== Bevor Sie beginnen

Sie müssen über die Anwendungsadministratorrolle verfügen.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *HTTPS-Zertifikat*.
. Klicken Sie auf *HTTPS-Zertifikatsignierungsanforderung herunterladen*.
. Speichern Sie die `<hostname>.csr` Datei:




== Nachdem Sie fertig sind

Sie können die Datei einer Zertifizierungsstelle zum Signieren bereitstellen und dann das signierte Zertifikat installieren.
