---
settings:
  name: Active IQ Unified Manager 9.9
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.9 Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/release-notes.html"
  - title: Los geht's
    entries:
    - title: Schnellstartinstallation für VMware vSphere
      url: "/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
