---
permalink: api-automation/concept-metrics-apis.html 
sidebar: sidebar 
keywords:  
summary: Active IQ Unified Manager bietet Ihnen einen Satz von APIs unter der Kategorie /Datacenter, mit denen Sie die Performance-Daten Ihrer Cluster und Storage-Objekte in einem Datacenter anzeigen können. Diese APIs rufen Performance-Daten der unterschiedlichen Storage-Objekte wie Cluster, Nodes, LUNs, Volumes ab. Aggregate und Storage VMs. 
---
= Anzeigen von Performance-Metriken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager stellt Ihnen unter dem eine Reihe von APIs zur Verfügung `/datacenter` Kategorien, mit denen Sie die Performance-Daten Ihrer Cluster und Storage-Objekte in einem Datacenter anzeigen können. Diese APIs rufen Performance-Daten der unterschiedlichen Storage-Objekte wie Cluster, Nodes, LUNs, Volumes ab. Aggregate und Storage VMs.

Der `/metrics` Und `/analytics` APIs bieten verschiedene Ansichten der Performance-Metriken, mit denen Sie verschiedene Detailebenen für die folgenden Storage-Objekte im Datacenter anzeigen können:

* Cluster
* Knoten
* Storage-VMs
* Aggregate
* Volumes
* LUNs


In der folgenden Tabelle wird ein Vergleich zwischen dem erstellt `/metrics` Und `/analytics` APIs hinsichtlich der Angaben zu den abgerufenen Leistungsdaten.

[cols="2*"]
|===
| Metriken | Analysen 


 a| 
Performance-Details für ein einzelnes Objekt. Beispiel: Der `+/datacenter/cluster/clusters/{key}/metrics+` Für eine API muss der Cluster-Schlüssel als eingegeben werden `path` Parameter zum Abrufen der Metriken für diesen spezifischen Cluster.
 a| 
Performance-Details für mehrere Objekte desselben Typs in einem Datacenter. Beispiel: Der `/datacenter/cluster/clusters/analytics` Die API ruft die kollektiven Kennzahlen aller Cluster in einem Datacenter ab.



 a| 
Beispiel für Performance-Kennzahlen für ein Storage-Objekt auf Basis des Zeitungsintervalls für den Abruf.
 a| 
Aggregierter Performance-Wert auf hoher Ebene für einen bestimmten Storage-Typ für einen bestimmten Zeitraum (über 72 Stunden).



 a| 
Grundlegende Details des Objekts werden abgerufen, z. B. Details zu einem Node oder Cluster.
 a| 
Es werden keine Details abgerufen.



 a| 
Kumulierte Zähler, wie z. B. Minimum, Maximum und die durchschnittlichen Performance-Werte über einen Zeitraum, werden für ein einzelnes Objekt abgerufen, wie z. B. Lesen, Schreiben, gesamt Und anderen Zählern. Beispiel: Der `+/datacenter/cluster/nodes/{key}/metrics+` API ruft (unter anderem) die folgenden Details für einen Knoten ab:

[listing]
----
 {
      "iops": {
        "local": {
          "others": 100.53,
          "read": 100.53,
          "total": 100.53,
          "write": 100.53
        },
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "latency": {
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "performance_capacity": {
        "available_iops_percent": 0,
        "free_percent": 0,
        "system_workload_percent": 0,
        "used_percent": 0,
        "user_workload_percent": 0
      },
      "throughput": {
        "other": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
---- a| 
Für alle Objekte desselben Typs wird ein einzelner aggregierter Wert angezeigt. Beispiel: Der `/datacenter/cluster/nodes/analytics` API ruft (unter anderem) die folgenden Werte für alle Knoten ab:

[listing]
----
 {
      "iops": 2757.5723,
      "latency": 0.8266,
      "throughput": 13254.6992,
      "utilization_percent": 58.6488,
      "period": 72,
      "performance_capacity": {
        "used_percent": 63.5317,
        "available_iops_percent": 60731.3086
      },
----


 a| 
Der Zeitbereich und die Probendaten basieren auf dem folgenden Zeitplan:dem Zeitbereich für die Daten. Beispiele können 1 h, 12 h, 1d, 2d, 3d, 15 D, 1 w, 1 m, 2 m, 3 m, 6 m Sie erhalten 1 Stunde Proben, wenn der Bereich mehr als 3 Tage (72 Std.), sonst sind es 5 Minuten Proben. Der Zeitraum für jeden Zeitbereich ist wie folgt:

* 1h: Kennzahlen der letzten Stunde, die über 5 Minuten erfasst wurden.
* 12h: Kennzahlen über die letzten 12 Stunden, die über 5 Minuten erfasst wurden.
* 1d: Kennzahlen des letzten Tages, abgetastet über 5 Minuten
* 2d: Kennzahlen der letzten 2 Tage, die über 5 Minuten erfasst wurden.
* 3d: Kennzahlen der letzten 3 Tage, die über 5 Minuten erfasst wurden.
* 15d: Kennzahlen der letzten 15 Tage, die über eine Stunde abgetastet wurden.
* 1w: Kennzahlen in der letzten Woche, die über 1 Stunde erfasst wurden.
* 1M: Kennzahlen im letzten Monat, die über 1 Stunde abgetastet wurden.
* 2 m: Kennzahlen der letzten 2 Monate, die über eine Stunde erfasst wurden.
* 3m: Kennzahlen in den letzten 3 Monaten, die über eine Stunde erfasst wurden.
* 6m: Kennzahlen der letzten 6 Monate, die über 1 Stunde abgetastet wurden.


Verfügbare Werte : 1h, 12h, 1d, 2d, 3d, 15 D, 1 w, 1 m, 2 m, 3 m, 6 m

Standardwert : 1h
 a| 
Über 72 Stunden, das sind 3 Tage. Die Dauer, über die diese Probe berechnet wird, wird im ISO-8601-Standardformat dargestellt.

|===
Die folgende Tabelle beschreibt das `/metrics` Und `/analytics` APIs im Detail.

[NOTE]
====
Die von diesen APIs zurückgegebenen IOPS- und Performance-Metriken sind beispielsweise doppelte Werte `100.53`. Das Filtern dieser Float-Werte durch die Pfeife („) und die Platzhalter (*)-Zeichen wird nicht unterstützt.

====
[cols="3*"]
|===
| HTTP-Verb | Pfad | Beschreibung 


 a| 
`GET`
 a| 
`+/datacenter/cluster/clusters/{key}/metrics+`
 a| 
Ruft die Performance-Daten (Beispiel und Zusammenfassung) für ein Cluster ab, das vom Eingabeparameter des Cluster-Schlüssels angegeben wurde. Informationen wie der Cluster-Schlüssel und die UUID, der Zeitbereich, IOPS, Durchsatz und die Anzahl der Proben werden zurückgegeben.



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
Ruft Performance-Kennzahlen auf hoher Ebene für alle Cluster in einem Datacenter ab. Sie können Ihre Ergebnisse nach den erforderlichen Kriterien filtern. Werte wie aggregierte IOPS, Durchsatz und Erfassungszeitraum (in Stunden) werden zurückgegeben.



 a| 
`GET`
 a| 
`+/datacenter/cluster/nodes/{key}/metrics+`
 a| 
Ruft Performance-Daten (Beispiel und Zusammenfassung) für einen Node ab, der durch den Eingabeparameter des Node-Schlüssels angegeben wurde. Informationen wie Node-UUID, Zeitbereich, Zusammenfassung der IOPS, Durchsatz, Latenz und Performance, die Anzahl der erfassten Proben und der verwendete Prozentsatz werden zurückgegeben.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
Ruft High-Level-Performance-Metriken für alle Nodes im Datacenter ab. Sie können Ihre Ergebnisse nach den erforderlichen Kriterien filtern. Informationen wie Node- und Cluster-Schlüssel und Werte wie aggregierte IOPS, Durchsatz und Erfassungszeitraum (in Stunden) werden zurückgegeben.



 a| 
`GET`
 a| 
`+/datacenter/storage/aggregates/{key}/metrics+`
 a| 
Ruft Performance-Daten (Probe und Zusammenfassung) für ein Aggregat ab, das durch den Eingabeparameter des Aggregatschlüssels angegeben wurde. Informationen wie z. B. Zeitraum, Zusammenfassung der IOPS, Latenz, Durchsatz und Performance-Kapazität, die Anzahl der für jeden Zähler gesammelten Proben und der Prozentsatz der genutzten Kapazität werden zurückgegeben.



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
Ruft Performance-Kennzahlen auf höchster Ebene für alle Aggregate in einem Datacenter ab. Sie können Ihre Ergebnisse nach den erforderlichen Kriterien filtern. Informationen wie Aggregat- und Cluster-Schlüssel und Werte wie aggregierte IOPS, Durchsatz und Erfassungszeitraum (in Stunden) werden zurückgegeben.



 a| 
`GET`
 a| 
`+/datacenter/storage/luns/{key}/metrics+`

`+/datacenter/storage/volumes/{key}/metrics+`
 a| 
Ruft Performance-Daten (Beispiel und Zusammenfassung) für eine LUN oder eine Dateifreigabe (Volume) ab, die vom Eingabeparameter der LUN- oder Volume-Taste angegeben wurde. Informationen, z. B. eine Zusammenfassung des minimalen, maximalen und durchschnittlichen Lese-, Schreib- und Gesamt-IOPS, der Latenz und des Durchsatzes Und die Anzahl der Proben, die für jeden Zähler gesammelt wurden, wird zurückgegeben.



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
Ruft Performance-Kennzahlen auf höchster Ebene für alle LUNs oder Volumes eines Datacenters ab. Sie können Ihre Ergebnisse nach den erforderlichen Kriterien filtern. Informationen wie Storage-VM- und Cluster-Schlüssel und Werte wie aggregierte IOPS, Durchsatz und Erfassungszeitraum (in Stunden) werden zurückgegeben.



 a| 
`GET`
 a| 
`+/datacenter/svm/svms/{key}/metrics+`
 a| 
Ruft die Performance-Daten (Beispiel und Zusammenfassung) für eine Storage-VM ab, die durch den Eingabeparameter des Storage-VM-Schlüssels angegeben wurde. Eine Zusammenfassung der IOPS basierend auf den einzelnen unterstützten Protokollen, z. B. `nvmf, fcp, iscsi`, und `nfs`, Durchsatz, Latenz und die Anzahl der gesammelten Proben zurückgegeben werden.



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
Abruf von Performance-Metriken auf höchster Ebene für alle Storage VMs in einem Datacenter Sie können Ihre Ergebnisse nach den erforderlichen Kriterien filtern. Informationen wie Storage-VM-UUID, aggregierte IOPS, Latenz, Durchsatz und der Erfassungszeitraum (in Stunden) werden zurückgegeben.



 a| 
`GET`
 a| 
`/datacenter/cluster/licensing/licenses` `+/datacenter/cluster/licensing/licenses/{key}+`
 a| 
Gibt die Details der auf den Clustern in Ihrem Rechenzentrum installierten Lizenzen zurück. Sie können Ihre Ergebnisse nach den erforderlichen Kriterien filtern. Informationen wie Lizenzschlüssel, Clusterschlüssel, Ablaufdatum und Umfang der Lizenz werden zurückgegeben. Sie können einen Lizenzschlüssel eingeben, um die Details einer bestimmten Lizenz abzurufen.

|===