---
permalink: api-automation/reference-intended-audience-for-this-guide.html 
sidebar: sidebar 
keywords:  
summary: Dieser Inhalt ist für Entwickler gedacht, die Applikationen erstellen, die über REST-APIs mit der Active IQ Unified Manager Software verbunden sind. 
---
= Zielgruppe für diesen Inhalt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieser Inhalt ist für Entwickler gedacht, die Applikationen erstellen, die über REST-APIs mit der Active IQ Unified Manager Software verbunden sind.

Storage-Administratoren und -Architekten. Diese Informationen bieten grundlegende Informationen dazu, wie die Unified Manager REST APIs verwendet werden können, um Client-Applikationen zum Managen und Überwachen von NetApp Storage-Systemen zu erstellen.

Sie sollten diese Informationen verwenden, wenn Sie den Storage-Provider, den ONTAP Cluster und Management-Administrations-APIs für das Management Ihres Storage verwenden möchten.

[NOTE]
====
Sie müssen eine der folgenden Rollen haben: Operator, Storage Administrator oder Application Administrator. Sie müssen die IP-Adresse oder den vollqualifizierten Domänennamen des Unified Manager Servers kennen, auf dem Sie die REST APIs ausführen möchten.

====