---
permalink: health-checker/concept-configuring-backup-for-windows.html 
sidebar: sidebar 
keywords: backup and restore on Windows,NetApp Snapshot 
summary: Active IQ Unified Manager unterstützt Backup und Restore mithilfe von NetApp Snapshots auf dem Windows Betriebssystem mithilfe von LUN über das iSCSI-Protokoll. 
---
= Backup wird unter Windows konfiguriert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager unterstützt Backup und Restore mithilfe von NetApp Snapshots auf dem Windows Betriebssystem mithilfe von LUN über das iSCSI-Protokoll.

Snapshot-basiertes Backup kann erstellt werden, während alle um-Services ausgeführt werden. Im Rahmen des Snapshots wird ein konsistenter Zustand der Datenbank erfasst, während das Backup eine globale Lesesperre auf die gesamte Datenbank setzt, die einen gleichzeitigen Schreibvorgang verhindert. Um Ihr Unified Manager System unter Windows durchzuführen und Backups und Restores mithilfe von NetApp Snapshots durchzuführen, sollten Sie zuerst Unified Manager Backup auf Snapshot basierend auf der Wartungskonsole konfigurieren.

Bevor Sie Ihre Active IQ Unified Manager Installation für das Snapshot Backup konfigurieren, müssen Sie die folgenden Konfigurationsaufgaben ausführen.

* Konfigurieren Sie den ONTAP Cluster
* Konfigurieren Sie den Windows-Hostcomputer

