---
permalink: health-checker/task-viewing-security-events-that-may-require-software-or-firmware-updates.html 
sidebar: sidebar 
keywords: upgrade events 
summary: 'Es gibt bestimmte Sicherheitsereignisse, die einen Wirkungsbereich von „Upgrade“ haben. Diese Ereignisse werden von der Active IQ-Plattform gemeldet. Sie erkennen Probleme, wenn für die Lösung ein Upgrade der ONTAP-Software, der Node-Firmware oder der Betriebssystem-Software \(for Security Advisories\) erforderlich ist.' 
---
= Anzeigen von Sicherheitsereignissen, für die möglicherweise Software- oder Firmware-Updates erforderlich sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt bestimmte Sicherheitsereignisse, die einen Impact-Bereich von „`Upgrade`“ haben. Diese Ereignisse werden von der Active IQ Plattform gemeldet. Sie erkennen Probleme, wenn für die Lösung ein Upgrade der ONTAP Software, der Node-Firmware oder der Betriebssystemsoftware (für Sicherheitsempfehlungen) erforderlich ist.



== Bevor Sie beginnen

Sie müssen über die Rolle „Operator“, „Application Administrator“ oder „Storage Administrator“ verfügen.



== Über diese Aufgabe

Möglicherweise möchten Sie für einige dieser Probleme sofortige Korrekturmaßnahmen durchführen, während andere Probleme möglicherweise bis zur nächsten geplanten Wartung warten können. Sie können alle diese Ereignisse anzeigen und sie Benutzern zuweisen, die die Probleme lösen können. Außerdem können Sie anhand dieser Liste bestimmte Ereignisse für Sicherheitsaspekte identifizieren, über die Sie keine Benachrichtigung erhalten möchten, damit Sie diese Ereignisse deaktivieren können.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Ereignisverwaltung*.
+
Standardmäßig werden alle aktiven (neuen und bestätigten) Ereignisse auf der Seite „Ereignismanagement-Bestand“ angezeigt.

. Wählen Sie im Menü Ansicht die Option *Ereignisse aktualisieren* aus.
+
Auf der Seite werden alle aktiven Sicherheitsereignisse für Upgrades angezeigt.


