---
permalink: install-vapp/task-upgrading-unified-manager-vapp.html 
sidebar: sidebar 
keywords:  
summary: Sie können ein Upgrade auf Unified Manager 9.9 nur von Instanzen von 9.7 oder 9.8 durchführen. 
---
= Upgrade Von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade auf Unified Manager 9.9 nur von Instanzen von 9.7 oder 9.8 durchführen.



== Über diese Aufgabe

Während des Upgrades ist Unified Manager nicht verfügbar. Vor dem Upgrade von Unified Manager sollten alle laufenden Vorgänge abgeschlossen werden.

Wenn Unified Manager mit einer Instanz von OnCommand Workflow Automation gekoppelt ist und für beide Produkte neue Versionen der Software zur Verfügung stehen, müssen Sie die beiden Produkte trennen und anschließend eine neue Workflow-Automatisierungsverbindung einrichten, nachdem Sie die Upgrades durchgeführt haben. Wenn Sie ein Upgrade auf nur eines der Produkte durchführen, müssen Sie sich nach dem Upgrade bei Workflow Automation anmelden und überprüfen, ob noch Daten von Unified Manager erfasst werden.
