---
permalink: install-linux/task-upgrading-openjdk-on-linux-ocum.html 
sidebar: sidebar 
keywords: OpenJDK,JRE 
summary: Sie können auf eine neuere Version von OpenJDK auf dem Linux-Server, auf dem Unified Manager installiert ist, aktualisieren, um Fehlerbehebungen für Sicherheitslücken zu erhalten. 
---
= Aktualisieren von OpenJDK unter Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können auf eine neuere Version von OpenJDK auf dem Linux-Server, auf dem Unified Manager installiert ist, aktualisieren, um Fehlerbehebungen für Sicherheitslücken zu erhalten.



== Bevor Sie beginnen

Sie müssen über Root-Rechte für das Linux-System verfügen, auf dem Unified Manager installiert ist.



== Über diese Aufgabe

Sie können OpenJDK-Versionen innerhalb von Versionsfamilien aktualisieren. Sie können beispielsweise ein Upgrade von OpenJDK 11.0.7 auf OpenJDK 11.0.9 durchführen, aber Sie können nicht direkt von OpenJDK 11 auf OpenJDK 12 aktualisieren.



== Schritte

. Melden Sie sich als Root-Benutzer auf dem Unified Manager-Hostcomputer an.
. Laden Sie die entsprechende Version von OpenJDK (64-Bit) auf das Zielsystem herunter.
. Beenden Sie die Unified Manager Services: `systemctl stop ocieau``systemctl stop ocie`
. Installieren Sie das neueste OpenJDK auf dem System.
. Starten Sie die Unified Manager Services: `systemctl start ocie``systemctl start ocieau`

