---
permalink: install-linux/task-downloading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Sie müssen die Unified Manager.zip-Datei von der NetApp Support Site herunterladen, um Unified Manager zu installieren. 
---
= Download Von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Unified Manager herunterladen``.zip`` Datei von der NetApp Support Site zur Installation von Unified Manager.



== Bevor Sie beginnen

Sie müssen Anmeldedaten für die NetApp Support-Website besitzen.



== Über diese Aufgabe

Sowohl für Red hat Enterprise Linux als auch für CentOS Systeme laden Sie das gleiche Unified Manager Installationspaket herunter.



== Schritte

. Melden Sie sich auf der NetApp Support Site an und navigieren Sie zur Seite *Download* für Unified Manager: https://["NetApp Support Website"]
. Wählen Sie die erforderliche Version von Unified Manager aus, und akzeptieren Sie die Endbenutzer-Lizenzvereinbarung (Endbenutzer License Agreement, EULA).
. Laden Sie die Installationsdatei für Unified Manager für Linux herunter, und speichern Sie die `.zip` Datei in ein Verzeichnis auf dem Zielsystem.
+
[NOTE]
====
Stellen Sie sicher, dass Sie die korrekte Version der Installationsdatei für Ihr Red hat Enterprise Linux-System herunterladen. Stellen Sie sicher, dass Sie die entsprechende Version von Unified Manager herunterladen, je nachdem, ob Red hat Enterprise Linux 7 oder 8 installiert ist``.zip`` Datei:

====
. Überprüfen Sie die Prüfsumme, um sicherzustellen, dass die Software ordnungsgemäß heruntergeladen wurde.

