---
permalink: data-protection/task-viewing-protection-relationships-from-storage-vms-page.html 
sidebar: sidebar 
keywords: storage VMs,viewing protection relationships 
summary: Mithilfe der Seite Storage VMs können Sie den Status der Disaster-Recovery-Beziehungen von vorhandenen Storage-VMs anzeigen. 
---
= Anzeigen von Sicherungsbeziehungen von der Seite Storage VMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Storage VMs können Sie den Status vorhandener Storage-VMs`' Disaster-Recovery-Beziehungen anzeigen.



== Bevor Sie beginnen

Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Auch Details zu den Sicherungsbeziehungen einschließlich Transfer- und Verzögerungsstatus, Quelle- und Zieldetails können Sie überprüfen. Sie können Berichte planen oder vorhandene Berichte in dem erforderlichen Format herunterladen. Mit der Schaltfläche *ein-/Ausblenden* können Sie die erforderlichen Spalten zu den Berichten hinzufügen, da diese standardmäßig nicht angezeigt werden.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *STORAGE* > *Storage VMs*.
. Wählen Sie im Menü *ANSICHT* die Option *Beziehung* > *Alle Beziehungen*.
+
Die Beziehungsansicht: Alle Beziehungen wird mit allen konfigurierten Speicher-VMs angezeigt.


